# Generated by Django 4.1.4 on 2023-01-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstarttime',
            name='time',
            field=models.TimeField(unique=True, verbose_name='Class Start Time'),
        ),
    ]
