# Generated by Django 4.1.4 on 2023-01-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_alter_classstarttime_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('classname', 'date'), name='One attendance for one class and a date'),
        ),
    ]
