name: HTTP Request Triggering git pull on server
  # You may pin to the exact commit or the version.
  # uses: fjogeleit/http-request-action@86014825e97036cd3e0903bbc72b3c5fff7474c4
  uses: fjogeleit/http-request-action@v1.12.0
  with:
    # Request URL
    url: https://attendance.amzdashboard.com/update_codebase
    # Request Method
    method: GET